### PR TITLE
KimLabDevCCFv001

### PR DESCRIPTION
**Pull request by faekronman**

### CODE REVIEW

**Comment by adamltyson** [comment]
As discussed on zoom, this is the [Kim Lab Developmental CCF](https://data.mendeley.com/datasets/2svx788ddf/1).

**Comment by adamltyson** [comment]
@vigji @FedeClaudi This atlas has multiple reference images (and eventually there will be more atlases with many references). Do you think we should continue to have one "main" reference and allow additional references, or move to a more general structure where one reference isn't necessarily the default? Lots of other atlases (e.g. zebrafish) are similar to this.

**Comment by adamltyson** [comment]
Hey @faekronman, sorry for the delay. Things have been busy on our end, but we'll look at this PR ASAP.

**Comment by JoeZiminski** [comment]
Hi @faekronman, my name is Joe and I've been working with Adam on incorporating this atlas, thanks for the submission. Apologies for the delay, the atlas generation is been worked through now and I will update here by the end of the week.

**Comment by JoeZiminski** [comment]
Hi @faekronman, apologies for the delay, we have a working version of the atlas generation script for a single reference and are in the process of adding the additional references. Thanks for your patience!

**Comment by adamltyson** [comment]
Hey @faekronman, this has taken a bit more work than we thought, and it's continued over in https://github.com/brainglobe/bg-atlasgen/pull/31. I'll close this PR, but https://github.com/brainglobe/bg-atlasgen/pull/31 should be done soon.

**Pull request closed without merging**
