### PR TITLE
Add WHS SD rat atlas

### PR DESCRIPTION
**Pull request by bkntr**
Version 4.0, from this link: https://www.nitrc.org/projects/whs-sd-atlas/

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Looks good to me! @adamltyson, @vigji ?

**Comment by vigji** [comment]
Looks good to me as well! I will try generating the atlas this evening and if everything's smooth also on my machine I'll merge. Thank you very much! @bkntr !

**Comment by adamltyson** [comment]
Yep, happy to merge once @vigji has got it running on his machine so we can upload the packaged atlas.

**Comment by vigji** [comment]
Tried to generate the atlas on my machine, only 2 things to report:
1. Add an additional dependency for `xmltodict`
2. I get the following message, are you aware of this area not having any label in the annotation?
```No labels found for DC-MID (1087)```

**Comment by bkntr** [comment]
1. True, I added xmltodict to the dependencies.
2. Yes I saw that as well, out of ~300 regions this is the only one that is missing a label, so I believe this is fine. This is missing from the atlas, so not much we can do about it anyway.

**Comment by vigji** [comment]
Ok, just wondering whether it makes sense to also remove it from the atlas regions, but that is up to you! Let me know, apart from that seems ready to merge! :)

**Comment by bkntr** [comment]
Yes it makes sense, I added a piece of code that removes missing structures.

**Comment by adamltyson** [comment]
Is this ready to merge now?

**Comment by vigji** [comment]
Good for me, yes!

**Comment by adamltyson** [comment]
Thanks for this @bkntr! I made one tiny change (https://github.com/brainglobe/bg-atlasgen/commit/53e23dbb858507079f54cbe5bf48a7e53fb230ad) to make sure the atlas is created in the same directory as others.

The atlas is now in the GIN repository, and can be seen with `brainglobe list`. I'll advertise it, and add it to the list of atlases on the website and docs soon.

**Pull request merged**
