### PR TITLE
Update Kim mouse atlas

### PR DESCRIPTION
**Pull request by adamltyson**
**WIP** 

Update the Kim mouse atlas and fix https://github.com/brainglobe/bg-atlasapi/issues/72 (among other issues).

The script now fetches the "raw" atlas materials from GIN, so it should work anywhere. 

There's one stupid issue, the generated meshes are in the wrong orientation, and I can't work out why (the images are fine). @FedeClaudi does the mesh generation assume a different origin?

I've also:
* Moved from vtkplotter  to vedo
* Update the requirements

### CODE REVIEW

**Comment by FedeClaudi** [comment]
I would suspect that the origin is flipped compared to the arrays like in brainrender?

In what way is the orientation incorrect?

**Comment by adamltyson** [comment]
Extracted root mesh overlaid on the brainrender default mesh:

Screenshot from 2020-10-23 16-58-05.

I think I'm doing something stupid though, because even reorienting the annotations image prior to mesh extraction didn't change the resulting meshes.

**Comment by FedeClaudi** [comment]
oh no that's not it then, it would be flipped left to right if anything but not rotated like that..

**Comment by vigji** [comment]
for you to know, the wrapping reorients both the stacks and the meshes; so you are not supposed to do any reorientation before invoking it, as long as you put the correct description in the orientation

**Comment by adamltyson** [comment]
> for you to know, the wrapping reorients both the stacks and the meshes; so you are not supposed to do any reorientation before invoking it, as long as you put the correct description in the orientation

Yeah I know, currently the atlas-specific script doesn't do anything, I was just playing around to see if I could come up with a hacky fix first.

**Comment by adamltyson** [comment]
If anyone gets a minute to look at this, that would be great. Apart from this issue (which must be pretty minor), I think this atlas is fixed. Otherwise I'll take another look next week.

**Comment by FedeClaudi** [comment]
I can't see anything that would explain why they'd be different like that.. and you've checked that the stacks are oriented the same way?

**Comment by adamltyson** [comment]
> I can't see anything that would explain why they'd be different like that.. and you've checked that the stacks are oriented the same way?

Yeah, they all look good (and the same as e.g. the Allen).

I've fixed the orientation of the meshes now (just by rotating the volume used to calculate them), it's not a good solution, but it works. In any case, I would suggest that most users of this atlas would use it mostly for the annotations, but use the Allen for most visualisation (the meshes are never going to be great, when the atlas was only created at 100um resolution in one axis).

Unless anyone has an issue with it, I'll merge this soon, and start uploading the atlases (some people in my lab want to test it).

@vigji what's going on with putting the atlas generation back into `bg-atlasapi`? How does this PR affect that work?

**Comment by FedeClaudi** [comment]
looks good for me

**Comment by vigji** [comment]
> @vigji what's going on with putting the atlas generation back into bg-atlasapi? How does this PR affect that work?

I am working on that with Nick; these scripts at the moment will be just moved there, so I will just make sure I update the kim atlas script in the PR

**Pull request merged**
